name: Terraform Plan

on: [workflow_dispatch]

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::160071257600:role/rlima-gh-actions-role
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9

    - name: Terraform Init 
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
